version: "3.7"

services:
  setup:
    container_name: redis-feast-gcp-setup
    build:
      context: ./
      dockerfile: ./setup/Dockerfile
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/tmp/keys/credentials.json:ro
    env_file:
      - ".env"
    environment:
      PATH: "${PATH}:/usr/local/gcloud/google-cloud-sdk/bin"
      GOOGLE_APPLICATION_CREDENTIALS: "/tmp/keys/credentials.json"
  jupyter:
    container_name: gcp-feast-jupyter
    build:
      context: ./
      dockerfile: ./jupyter/Dockerfile
    volumes:
      - ./:/home/jovyan/work
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/tmp/keys/credentials.json:ro
    ports:
      - 8888:8888
    env_file:
      - ".env"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/tmp/keys/credentials.json"